import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { queryClient } from "@/providers/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import Sidebar from "@/components/navigation/Sidebar";
import { SpinnerProvider } from "@/providers/spinner-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <SpinnerProvider>
            <SidebarProvider>
              <QueryClientProvider client={queryClient}>
                <Sidebar>{children}</Sidebar>
              </QueryClientProvider>
            </SidebarProvider>
          </SpinnerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
